### ISSUE TITLE
Unklar warning messages in logs

### ISSUE THREAD

**Issue by rolandschuetz** [terhuerne/Contao-Aggregator#20]
Hello,

I have setup the aggregator and it seems to work perfectly. The latest messages are up to date and are displayed correctly.

Still, a lot of warnings are collected in my log files. The file /system/modules/aggregator/cache/1.json.cache exists as this point in time and I believe it always did. The owner is the apache user and Contao needs to be able to write the file, otherwise the messages wouldn't regularly update.

`/system/modules/aggregator/cache/1.json.cache): failed to open stream: Permission denied in /system/modules/aggregator/classes/AggregatorEngine.php on line 447
#0 [internal function]: __error(2, 'fopen(/data/web...', '/data/web/www/v...', 447, Array)
#1 /system/modules/aggregator/classes/AggregatorEngine.php(447): fopen('/data/web/www/v...', 'w')
#2 /system/modules/aggregator/classes/AggregatorEngine.php(320): Aggregator\AggregatorEngine->parseDataToCache(Array, '1', Array, 'facebook')
#3 /system/modules/core/controllers/FrontendCron.php(100): Aggregator\AggregatorEngine->checkForAggregatorUpdates()
#4 /system/cron/cron.php(20): Contao\FrontendCron->run()
#5 {main}

[30-Jan-2016 00:00:03 GMT] 
PHP Warning: fwrite() expects parameter 1 to be resource, boolean given in /system/modules/aggregator/classes/AggregatorEngine.php on line 448
#0 [internal function]: __error(2, 'fwrite() expect...', '/data/web/www/v...', 448, Array)
#1 /system/modules/aggregator/classes/AggregatorEngine.php(448): fwrite(false, '[{"author":{"na...')
#2 /system/modules/aggregator/classes/AggregatorEngine.php(320): Aggregator\AggregatorEngine->parseDataToCache(Array, '1', Array, 'facebook')
#3 /system/modules/core/controllers/FrontendCron.php(100): Aggregator\AggregatorEngine->checkForAggregatorUpdates()
#4 /system/cron/cron.php(20): Contao\FrontendCron->run()
#5 {main}

[30-Jan-2016 00:00:03 GMT] 
PHP Warning: fclose() expects parameter 1 to be resource, boolean given in /system/modules/aggregator/classes/AggregatorEngine.php on line 449
#0 [internal function]: __error(2, 'fclose() expect...', '/data/web/www/v...', 449, Array)
#1 /system/modules/aggregator/classes/AggregatorEngine.php(449): fclose(false)
#2 /system/modules/aggregator/classes/AggregatorEngine.php(320): Aggregator\AggregatorEngine->parseDataToCache(Array, '1', Array, 'facebook')
#3 /system/modules/core/controllers/FrontendCron.php(100): Aggregator\AggregatorEngine->checkForAggregatorUpdates()
#4 /system/cron/cron.php(20): Contao\FrontendCron->run()
#5 {main}

[30-Jan-2016 00:00:03 GMT] ... same warnings for 2.json.cache and 3.json.cache`

Any idea how to fix this issue?

**Comment by terhuerne** [comment]
Hello Roland, can you give me some more information about your system setup? Which PHP-Version do you use?

**Comment by rolandschuetz** [comment]
PHP Version 5.4.16 on a linux machine with apache.

**Comment by rolandschuetz** [comment]
Any ideas?
